### ISSUE TITLE
`<filter>` support

### ISSUE THREAD

**Issue by jwmcglynn** [jwmcglynn/donner#151]
Implement filter support, based on the spec here: https://www.w3.org/TR/filter-effects/

# Stage 1: MVP

- [x] Add initial `<filter>` element
- [x] Create initial filter primitive, `<feGaussianBlur>`, with minimal functionality
- [x] Add support for `filter` presentation attribute https://www.w3.org/TR/filter-effects/#FilterProperty
- [x] Skia renderer backend integration

This should be validated by rendering the donner splash logo

# Stage 2: Full implementation

- [ ] Scope missing features based on MVP
- [ ] Support for all `<filter>` and `<feGaussianBlur>` features
- [ ] Support for additional filter primitives
- [ ] External resource handling (using a callback-based approach)
